ルーム入室画面でトーストを表示
jphacks/D_2208 pull request #115
Opened 2022-10-21 09:47 UTC by averak

2022-10-21 11:13 UTC, ygkn requested changes

2022-10-21 11:13 UTC, ygkn commented on app/src/main/pointer/src/components/JoinRoomForm.tsx
> +    } catch (error: any) {
```suggestion
    } catch (error: unknown) {
```

2022-10-22 02:40 UTC, Ran350 approved these changes
ふっ

2022-10-22 02:41 UTC, ygkn approved these changes

2022-10-22 03:01 UTC, merged